### ISSUE TITLE
My score is too low

### ISSUE THREAD

**Issue by DanojNL** [BartvonMeijenfeldt/fussball_rankings#3]
Hi,

I think there is a bug in the rating overview. My score is 1314.8, but it's too low. I think the right score should be above Liveris (1669.4). Can you look into it? Thanks!

![image](https://user-images.githubusercontent.com/36549576/195072829-32f4c1c8-2c51-40d9-8c35-491af7d331c5.png)

**Comment by DanojNL** [comment]
Huh, just checked the latest score and I dropped to place 14, below Timo. I think this is definitely not right.

Please, can you fix this? 

![image](https://user-images.githubusercontent.com/36549576/195073309-39964e66-28d4-444f-a7da-0102aa7b3a34.png)

**Comment by PeterBanpas** [comment]
Yeah for me as well. Please fix this issue @BartvonMeijenfeldt @BastiaanRudolf

**Comment by BMMohammed** [comment]
@DanojNL @PeterBanpas git gud!

**Comment by BastiaanRudolf** [comment]
@DanojNL @PeterBanpas can you please share the steps to reproduce? Works when I do it.

**Comment by BartvonMeijenfeldt** [comment]
> Hi,
> 
> I think there is a bug in the rating overview. My score is 1314.8, but it's too low. I think the right score should be above Liveris (1669.4). Can you look into it? Thanks!
> 
> ![image](https://user-images.githubusercontent.com/36549576/195072829-32f4c1c8-2c51-40d9-8c35-491af7d331c5.png)

This works as intended read the documentation.

**Comment by BartvonMeijenfeldt** [comment]
> Huh, just checked the latest score and I dropped to place 14, below Timo. I think this is definitely not right.
> 
> Please, can you fix this?
> 
> ![image](https://user-images.githubusercontent.com/36549576/195073309-39964e66-28d4-444f-a7da-0102aa7b3a34.png)

Found a hacky way to solve this by adding a few games, unstable solution.
