### ISSUE TITLE
Rating calculator

### ISSUE THREAD

**Issue by YashinVK** [BartvonMeijenfeldt/fussball_rankings#4]
Rating calculator is not working is missing init

**Comment by BartvonMeijenfeldt** [comment]
Updated in last commit (moved barto directory to TLD), can you check if you can get the rating_change_calculator.py working now?

**Comment by YashinVK** [comment]
Hi Bart,

I might be doing something wrong:

![image](https://user-images.githubusercontent.com/115647861/201474196-84bd4784-46b0-417d-a428-1986c3e1e835.png)

**Comment by BartvonMeijenfeldt** [comment]
Hey Yashin,

In general the packages are only using built-in Python functionality but for a few things it is using the scipy packages which needs to be installed first. From the environment from which you are running this package you should install the package with the command `pip install scikit-learn` and then it should run properly

**Comment by YashinVK** [comment]
Yes! Everything works, thanks!
![image](https://user-images.githubusercontent.com/115647861/201518492-19281e34-bfa9-4ceb-9fb5-d8ad99a601ca.png)
